### ISSUE TITLE
Gradle Build Variants的问题

### ISSUE THREAD

**Issue by yankai-victor** [yanglw/Android-Gradle-Examples#1]
今天使用Flavor的时候遇到问题 发现了这个examples 写的很不错

**Comment by yanglw** [comment]
不知道为什么在 issue 里，看不到你的问题内容，只能在通知邮件中看到。现在把邮件中的问题在这里列出来。

> 今天使用Flavor的时候遇到问题 发现了这个examples 写的很不错
> --------------问题分割线-------------------------------
> 我默认的包名为com.base
> 里面有MainActivity和CustomerView自定义控件
> 定义了一个Flavor 包名为com.a 修改了res的部分文件
> 运行这个Flavor的时候报错提示我在MainActivity里找不到com.a.CustomerView
> 这是为什么呢？

`CustomerView` 类，应该是在 `main/java/com/base` 目录下，当你在布局文件中使用的时候，你需要使用 `com.base.CustomerView` ，而不是 `com.a.CustomerView` 。

`flavor` 可以当做是对 `main` 的一个补充或者修改，最终 `flavor` 中的内容会和 `main` 中的内容进行合并。你可以在 `flavor` 中使用 `main` 中的内容，也可以在 `main` 中使用对应的 `flavor` 中的内容。如果你的 `main` 或者 `flavor` 中存在类 `com.a.CustomerView` 则可以使用；否则就无法使用。
